//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.ApplicationCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.ApplicationCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công.
        /// </summary>
        internal static string addNotSuccess {
            get {
                return ResourceManager.GetString("addNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công.
        /// </summary>
        internal static string addSuccess {
            get {
                return ResourceManager.GetString("addSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cửa hàng không vượt quá 20 ký tự.
        /// </summary>
        internal static string beyondLengthStoreCode {
            get {
                return ResourceManager.GetString("beyondLengthStoreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày tháng năm không vượt phải năm trong khoảng (01/01/1900 - 01/01/2021).
        /// </summary>
        internal static string datetime {
            get {
                return ResourceManager.GetString("datetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá không thành công.
        /// </summary>
        internal static string deleteNotSuccess {
            get {
                return ResourceManager.GetString("deleteNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá dữ liệu thành công.
        /// </summary>
        internal static string deleteSuccess {
            get {
                return ResourceManager.GetString("deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cửa hàng đã tồn tại. Vui lòng kiểm tra lại.
        /// </summary>
        internal static string duplicateStoreCode {
            get {
                return ResourceManager.GetString("duplicateStoreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu thành công.
        /// </summary>
        internal static string getSuccess {
            get {
                return ResourceManager.GetString("getSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy.
        /// </summary>
        internal static string notFound {
            get {
                return ResourceManager.GetString("notFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi không tồn tại.
        /// </summary>
        internal static string recordNotFound {
            get {
                return ResourceManager.GetString("recordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ cửa hàng không được để trống.
        /// </summary>
        internal static string requiredStoreAddress {
            get {
                return ResourceManager.GetString("requiredStoreAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã cửa hàng không được để trống.
        /// </summary>
        internal static string requiredStoreCode {
            get {
                return ResourceManager.GetString("requiredStoreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cửa hàng không được để trống.
        /// </summary>
        internal static string requiredStoreName {
            get {
                return ResourceManager.GetString("requiredStoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id không tồn tại trong hệ thống.
        /// </summary>
        internal static string storeIdNotFound {
            get {
                return ResourceManager.GetString("storeIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa không thành công.
        /// </summary>
        internal static string updateNotSuscess {
            get {
                return ResourceManager.GetString("updateNotSuscess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thành công.
        /// </summary>
        internal static string updateSuccess {
            get {
                return ResourceManager.GetString("updateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sai định dạng.
        /// </summary>
        internal static string validateError {
            get {
                return ResourceManager.GetString("validateError", resourceCulture);
            }
        }
    }
}
